# Generated by Django 3.2 on 2023-02-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название вашей категории', max_length=256, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='(Пример: films)', unique=True, verbose_name='Идентификатор категории')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название вашей категории', max_length=256, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='(Пример: films)', unique=True, verbose_name='Идентификатор категории')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название произведения', max_length=256, verbose_name='Название произведения')),
                ('year', models.DateField(verbose_name='Дата публикации')),
                ('description', models.TextField(help_text='Опишите произведение', verbose_name='Описание произведения')),
                ('categories', models.ForeignKey(blank=True, help_text='Выберите категорию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='reviews.categories', verbose_name='Категория')),
                ('genres', models.ForeignKey(blank=True, help_text='Выберите жанр', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre', to='reviews.categories', verbose_name='Жанр')),
            ],
        ),
    ]
